### PR TITLE
Feedback from Tomasz

### PR DESCRIPTION
**Pull request by donotdespair**
Hi @DjangoTG 

This is a nice submission! Thanks!

I provide some more suggestions in my commits to this pull request (BTW please ignore all the commits beginning with **Revert**, I had a bit of troubles processing my changes - everything should be fine on your side).

May I suggest several extensions:

- [ ] every time you report a result, such as the autocorrelograms or data plots, please comment briefly on these outputs in the context of your project
- [ ] I suggest performing integration order determination of all variables, providing sample code for one. Please draw conclusions from these outcomes, e.g. for determining the mean of the Minnesota prior.

I am looking forward to your new submissions!

### CODE REVIEW

**Comment by donotdespair** [comment]
Hi @DjangoTG 

It's OK to close a pull request and not introduce the changes. Please comment here point by point on what you introduced and what not, and leave some brief motivation. Thanks.

**Review by DjangoTG — APPROVED** [review]

**Review by DjangoTG — APPROVED** [review]

**Review by DjangoTG — COMMENTED** [review]
This is related to previous project idea (Income Inequality), will manually make changes in index to  improve graphs.

**Review by DjangoTG — COMMENTED** [review]
Changed in previous commit.

**Review by DjangoTG — COMMENTED** [review]
Have incorporated change manually.

**Comment by DjangoTG** [comment]
Incorporated several changes manually, but most were already incorporated or relate to the Income Inequality project.

**Pull request closed without merging**
